# Local Setting
baseurl: ""
url: ""

theme: just-the-docs
title: "Queenlang"
color_scheme: "dark"
footer_content: "Copyright &copy; 2019-2023 Extremely Distributed Technologies S.R.L. Romania. Designed with ❤️ in Vienna and Cluj-Napoca."
